// Image-first output formats
// Each format maps directly to a DALL-E image generation with specific dimensions and style
export const OUTPUT_FORMATS = {
  BANNER_AD: {
    name: 'Banner Ad',
    platform: 'Digital Ads',
    description: 'Wide horizontal banner for websites and display ads',
    width: 1200,
    height: 628,
    aspect: '1.91:1',
    icon: '▬',
  },
  POSTER: {
    name: 'Poster',
    platform: 'Print & Digital',
    description: 'Tall portrait poster for print or digital display',
    width: 800,
    height: 1100,
    aspect: '3:4',
    icon: '❐',
  },
  FLYER: {
    name: 'Flyer',
    platform: 'Print & Digital',
    description: 'Compact flyer for events and promotions',
    width: 800,
    height: 1000,
    aspect: '4:5',
    icon: '📄',
  },
  INSTAGRAM_POST: {
    name: 'Instagram Post',
    platform: 'Instagram',
    description: 'Square post optimised for Instagram feed',
    width: 1080,
    height: 1080,
    aspect: '1:1',
    icon: '📸',
  },
  INSTAGRAM_STORY: {
    name: 'Instagram Story',
    platform: 'Instagram / TikTok',
    description: 'Vertical story or reel cover',
    width: 1080,
    height: 1920,
    aspect: '9:16',
    icon: '📱',
  },
  YOUTUBE_THUMBNAIL: {
    name: 'YouTube Thumbnail',
    platform: 'YouTube',
    description: 'Bold thumbnail to maximise click-through rate',
    width: 1280,
    height: 720,
    aspect: '16:9',
    icon: '▶',
  },
};